version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring

  postgres_exporter:
    image: quay.io/prometheus-community/postgres-exporter
    restart: always
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}/${POSTGRES_DATABASE_NAME}?sslmode=disable"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - monitoring
    depends_on:
      - node-exporter
      - postgres_exporter
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' # Thêm command để chỉ định file cấu hình

  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - prometheus
      - node-exporter
    ports:
      - "6868:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
  prometheus_data:
